[CIM]
periodic_boundary = true

[visuals]
target_particle_id = 47

[files]
static_input = "./static.txt"
dynamic_input = "./dynamic.txt"
output = "./output.txt"

[statistics]
times = "./times.txt"
run_stats = true
